### ISSUE TITLE
Improve error catching when service has missing configuration

### ISSUE THREAD

**Issue by zajcu** [Cognifide/knotx#199]
When service has missing configuration following error occurs during fragment processing:

`java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_91]
	at com.cognifide.knotx.knot.view.service.ServiceEngine.mergeWithConfiguration(ServiceEngine.java:72) ~[knotx-example-monolith-0.6.0-SNAPSHOT-fat.jar:na]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[knotx-example-monolith-0.6.0-SNAPSHOT-fat.jar:na]
	at rx.observers.Subscribers$5.onNext(Subscribers.java:235) ~[knotx-example-monolith-0.6.0-SNAPSHOT-fat.jar:na]`

Knot.x should send 500, with proper error in log.

**Comment by marcinczeczko** [comment]
Fixed
